### ISSUE TITLE
compile it on my debian 10, but report need libgee-1.0, how can I get it?

### ISSUE THREAD

**Issue by carlos444** [ondratu/mmarchitect#1]
Package gee-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gee-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gee-1.0' found
make[1]: *** [Makefile:87: pkgcheck] Error 1
make[1]: Leaving directory '/root/mmarchitect-0.5.0'
make: *** [Makefile:111: configure] Error 2

It seems the newest libgee is 0.8

**Comment by ondratu** [comment]
Hi, you need to install ``libgee-0.8-dev``. I'm working on new build system (mason & ninja) in ``meson`` branch, and some needed fixes in ``ng`` branch. But this build does not work now. I hope that i will have time to work on next month.

**Comment by carlos444** [comment]
> Hi, you need to install `libgee-0.8-dev`. I'm working on new build system (mason & ninja) in `meson` branch, and some needed fixes in `ng` branch. But this build does not work now. I hope that i will have time to work on next month.

OK and thank you, I wait for the new release.
